In [2]:
import pandas as pd
import numpy as np
from numpy import *
import time
import matplotlib.pyplot as plt
from pandas import DataFrame
from scipy.spatial.distance import pdist
from sklearn.cluster import KMeans, Birch, DBSCAN

In [3]:
dna = pd.read_csv('codon_usage.csv')
dna['Kingdom'].value_counts()

bct    2919
vrl    2831
pln    2523
vrt    2077
inv    1345
mam     572
phg     220
rod     215
pri     180
arc     126
plm      18
Name: Kingdom, dtype: int64

In [6]:
dna

,Kingdom,DNAtype,SpeciesID,Ncodons,SpeciesName,UUU,UUC,UUA,UUG,CUU,...,CGG,AGA,AGG,GAU,GAC,GAA,GAG,UAA,UAG,UGA
0,vrl,0,100217,1995,Epizootic haematopoietic necrosis virus,0.01654,0.01203,0.00050,0.00351,0.01203,...,0.00451,0.01303,0.03559,0.01003,0.04612,0.01203,0.04361,0.00251,0.00050,0.00000
1,vrl,0,100220,1474,Bohle iridovirus,0.02714,0.01357,0.00068,0.00678,0.00407,...,0.00136,0.01696,0.03596,0.01221,0.04545,0.01560,0.04410,0.00271,0.00068,0.00000
2,vrl,0,100755,4862,Sweet potato leaf curl virus,0.01974,0.02180,0.01357,0.01543,0.00782,...,0.00596,0.01974,0.02489,0.03126,0.02036,0.02242,0.02468,0.00391,0.00000,0.00144
3,vrl,0,100880,1915,Northern cereal mosaic virus,0.01775,0.02245,0.01619,0.00992,0.01567,...,0.00366,0.01410,0.01671,0.03760,0.01932,0.03029,0.03446,0.00261,0.00157,0.00000
4,vrl,0,100887,22831,Soil-borne cereal mosaic virus,0.02816,0.01371,0.00767,0.03679,0.01380,...,0.00604,0.01494,0.01734,0.04148,0.02483,0.03359,0.03679,0.00000,0.00044,0.00131
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13021,pri,0,9601,1097,Pongo pygmaeus abelii,0.02552,0.03555,0.00547,0.01367,0.01276,...,0.00820,0.01367,0.01094,0.01367,0.02279,0.02005,0.04102,0.00091,0.00091,0.00638
13022,pri,1,9601,2067,mitochondrion Pongo pygmaeus abelii,0.01258,0.03193,0.01984,0.00629,0.01451,...,0.00145,0.00000,0.00048,0.00194,0.01306,0.01838,0.00677,0.00242,0.00097,0.01887
13023,pri,1,9602,1686,mitochondrion Pongo pygmaeus pygmaeus,0.01423,0.03321,0.01661,0.00356,0.01127,...,0.00000,0.00000,0.00000,0.00178,0.01661,0.02788,0.00297,0.00356,0.00119,0.02017
13024,pri,0,9606,40662582,Homo sapiens,0.01757,0.02028,0.00767,0.01293,0.01319,...,0.01142,0.01217,0.01196,0.02178,0.02510,0.02896,0.03959,0.00099,0.00079,0.00156
13025,pri,1,9606,8998998,mitochondrion Homo sapiens,0.01778,0.03724,0.01732,0.00600,0.01689,...,0.00083,0.00041,0.00041,0.00451,0.01402,0.01651,0.00783,0.00156,0.00114,0.02161

In [4]:
data_split1 = dna.sample(frac=0.1, random_state=0, axis=0)

In [5]:
data_split1

,Kingdom,DNAtype,SpeciesID,Ncodons,SpeciesName,UUU,UUC,UUA,UUG,CUU,...,CGG,AGA,AGG,GAU,GAC,GAA,GAG,UAA,UAG,UGA
8184,pln,0,5501,13160,Coccidioides immitis,0.01527,0.02485,0.00471,0.01649,0.01778,...,0.00646,0.00866,0.00494,0.02994,0.02804,0.03153,0.03404,0.00091,0.00038,0.00099
5797,arc,0,69014,657527,Thermococcus kodakarensis KOD1,0.01312,0.02992,0.00417,0.00573,0.02091,...,0.00321,0.01254,0.03127,0.01542,0.03202,0.02708,0.06088,0.00067,0.00049,0.00242
5519,bct,0,47882,2692,Pseudomonas straminea,0.00669,0.03529,0.00000,0.00371,0.00334,...,0.00037,0.00000,0.00111,0.02006,0.03826,0.02043,0.02415,0.00149,0.00000,0.00186
5567,bct,0,52561,9560,Desulfovibrio desulfuricans,0.01611,0.02050,0.00084,0.00366,0.01789,...,0.00659,0.00314,0.00345,0.01726,0.03400,0.03923,0.01695,0.00073,0.00178,0.00063
8816,inv,0,186283,4029,Drosophila parabipectinata,0.01539,0.02408,0.00546,0.01638,0.01018,...,0.00621,0.00546,0.00521,0.02234,0.03524,0.02333,0.04219,0.00099,0.00124,0.00025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6136,pln,0,103999,4265,Codonopsis lanceolata,0.01829,0.01829,0.00516,0.01712,0.02040,...,0.00305,0.00868,0.01266,0.03494,0.02063,0.02931,0.04127,0.00211,0.00047,0.00211
6600,pln,0,21020,5208,Castanea sativa,0.02477,0.01728,0.01056,0.02035,0.02189,...,0.00346,0.01094,0.01824,0.03303,0.01402,0.02765,0.03725,0.00173,0.00077,0.00192
9169,inv,0,37776,1775,Actias selene,0.01408,0.02028,0.00732,0.01577,0.01690,...,0.00225,0.00901,0.01070,0.02535,0.02085,0.04732,0.01803,0.00056,0.00000,0.00000
2908,bct,0,114417,2118,Lactococcus phage ul36.1,0.03588,0.00661,0.02361,0.01228,0.01983,...,0.00189,0.01605,0.00236,0.04060,0.01605,0.08215,0.01889,0.00425,0.00047,0.00236
1453,vrl,0,290030,1683,Malvastrum yellow vein Yunnan virus,0.01426,0.02733,0.02317,0.01248,0.01901,...,0.00951,0.01426,0.01545,0.03090,0.01188,0.03506,0.02377,0.00178,0.00357,0.00119

In [8]:
data_tmp1 = dna[~dna.index.isin(data_split1.index)]
data_split2 = data_tmp1.sample(frac=0.1, random_state=0, axis=0)
data_split2

,Kingdom,DNAtype,SpeciesID,Ncodons,SpeciesName,UUU,UUC,UUA,UUG,CUU,...,CGG,AGA,AGG,GAU,GAC,GAA,GAG,UAA,UAG,UGA
3966,bct,0,180862,1022,Bacillus thuringiensis serovar toumanoffi,0.02446,0.01076,0.03229,0.00685,0.01566,...,0.00000,0.00196,0.00098,0.04207,0.01174,0.04892,0.01174,0.00098,0.00196,0.00000
11223,vrt,0,38577,2881,Bufo arenarum,0.02152,0.01666,0.00833,0.01944,0.01978,...,0.00382,0.01493,0.01319,0.03159,0.02152,0.02881,0.02013,0.00104,0.00000,0.00069
12673,rod,0,10117,73391,Rattus rattus,0.01759,0.02473,0.00503,0.01222,0.01106,...,0.00929,0.00959,0.01071,0.02157,0.02977,0.02545,0.04013,0.00086,0.00048,0.00117
11959,vrt,1,88713,1784,mitochondrion Rondeletia loricata,0.04036,0.02635,0.02354,0.00953,0.02859,...,0.00392,0.00000,0.00000,0.00897,0.01009,0.01513,0.01009,0.00224,0.00112,0.02298
3162,bct,0,31537,7680,Lactococcus phage c2,0.03060,0.01641,0.03086,0.01849,0.01380,...,0.00065,0.01250,0.00391,0.02813,0.03008,0.05286,0.01914,0.00299,0.00091,0.00156
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11250,vrt,1,399539,1107,mitochondrion Timon pater tangitana,0.02349,0.03433,0.03704,0.00452,0.04246,...,0.00181,0.00000,0.00000,0.00452,0.01265,0.01445,0.00181,0.00181,0.00090,0.02800
9093,inv,0,34573,3276,Nautilus pompilius,0.02930,0.02869,0.00794,0.01801,0.01587,...,0.00366,0.01557,0.00549,0.02656,0.03480,0.03297,0.02808,0.00000,0.00031,0.00031
2596,vrl,0,59509,57775,Lumpy skin disease virus,0.05291,0.00592,0.05186,0.01317,0.01134,...,0.00061,0.01740,0.00486,0.04997,0.00933,0.04829,0.00744,0.00258,0.00047,0.00033
2760,vrl,0,80942,8183,Batai virus,0.03141,0.01809,0.03165,0.01564,0.01198,...,0.00049,0.01845,0.01393,0.03226,0.01308,0.04045,0.01821,0.00110,0.00000,0.00024
9482,inv,0,6100,4535,Aequorea victoria,0.01499,0.02734,0.00882,0.01323,0.02580,...,0.00000,0.01676,0.00066,0.07365,0.02161,0.05314,0.02095,0.00485,0.00000,0.00000

In [50]:
dna.drop(columns=['DNAtype','SpeciesID','Ncodons','SpeciesName'],inplace=True)
data = dna.iloc[:,1:].astype(float)
data

,UUU,UUC,UUA,UUG,CUU,CUC,CUA,CUG,AUU,AUC,...,CGG,AGA,AGG,GAU,GAC,GAA,GAG,UAA,UAG,UGA
0,0.01654,0.01203,0.00050,0.00351,0.01203,0.03208,0.00100,0.04010,0.00551,0.02005,...,0.00451,0.01303,0.03559,0.01003,0.04612,0.01203,0.04361,0.00251,0.00050,0.00000
1,0.02714,0.01357,0.00068,0.00678,0.00407,0.02849,0.00204,0.04410,0.01153,0.02510,...,0.00136,0.01696,0.03596,0.01221,0.04545,0.01560,0.04410,0.00271,0.00068,0.00000
2,0.01974,0.02180,0.01357,0.01543,0.00782,0.01111,0.01028,0.01193,0.02283,0.01604,...,0.00596,0.01974,0.02489,0.03126,0.02036,0.02242,0.02468,0.00391,0.00000,0.00144
3,0.01775,0.02245,0.01619,0.00992,0.01567,0.01358,0.00940,0.01723,0.02402,0.02245,...,0.00366,0.01410,0.01671,0.03760,0.01932,0.03029,0.03446,0.00261,0.00157,0.00000
4,0.02816,0.01371,0.00767,0.03679,0.01380,0.00548,0.00473,0.02076,0.02716,0.00867,...,0.00604,0.01494,0.01734,0.04148,0.02483,0.03359,0.03679,0.00000,0.00044,0.00131
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13021,0.02552,0.03555,0.00547,0.01367,0.01276,0.02097,0.00820,0.03555,0.01459,0.03920,...,0.00820,0.01367,0.01094,0.01367,0.02279,0.02005,0.04102,0.00091,0.00091,0.00638
13022,0.01258,0.03193,0.01984,0.00629,0.01451,0.05322,0.07644,0.01258,0.03096,0.06386,...,0.00145,0.00000,0.00048,0.00194,0.01306,0.01838,0.00677,0.00242,0.00097,0.01887
13023,0.01423,0.03321,0.01661,0.00356,0.01127,0.05042,0.09609,0.01068,0.02728,0.06643,...,0.00000,0.00000,0.00000,0.00178,0.01661,0.02788,0.00297,0.00356,0.00119,0.02017
13024,0.01757,0.02028,0.00767,0.01293,0.01319,0.01959,0.00715,0.03964,0.01600,0.02082,...,0.01142,0.01217,0.01196,0.02178,0.02510,0.02896,0.03959,0.00099,0.00079,0.00156
13025,0.01778,0.03724,0.01732,0.00600,0.01689,0.03854,0.07000,0.01308,0.03391,0.05137,...,0.00083,0.00041,0.00041,0.00451,0.01402,0.01651,0.00783,0.00156,0.00114,0.02161

In [61]:
k = Birch(n_clusters = 5, threshold = 0.001)
k.fit(data)
print(k.cluster_centers_)

AttributeError: 'Birch' object has no attribute 'cluster_centers_'

In [1]:
data

NameError: name 'data' is not defined

In [53]:
classed = pd.concat([dna["Kingdom"],data["class"]], axis=1)
classed

      Kingdom  class
0         vrl      0
1         vrl      0
2         vrl      0
3         vrl      0
4         vrl      0
...       ...    ...
13021     pri      0
13022     pri      0
13023     pri      0
13024     pri      0
13025     pri      0

[13026 rows x 2 columns]

In [46]:
compare = classed[['Kingdom','class']]
class0 = compare[compare['class']==0]
class1 = compare[compare['class']==1]
class2 = compare[compare['class']==2]
class3 = compare[compare['class']==3]
class4 = compare[compare['class']==4]

cluster = [class0,class1,class2,class3,class4]

verify = []
for c in cluster:
    vrl = len(c[c['Kingdom']=='vrl'])
    bct = len(c[c['Kingdom']=='bct'])
    pln = len(c[c['Kingdom']=='pln'])
    vrt = len(c[c['Kingdom']=='vrt'])
    inv = len(c[c['Kingdom']=='inv'])
    verify.append([vrl,bct,pln,vrt,inv])
answer = pd.DataFrame(verify)
answer.columns = ['vrl','bct','pln','vrt','inv']

print(answer)

    vrl   bct   pln   vrt  inv
0   362   937  1042    82  510
1  2167   626   797   153  413
2     1     0     4  1532   34
3    39  1220   116     3   45
4   262   136   564   307  343