In [53]:
import pandas as pd
import numpy as np
from numpy import *
import time
import matplotlib.pyplot as plt
from pandas import DataFrame

In [116]:
dna = pd.read_csv('C:/Users/fader/Desktop/clustering/codon_usage.csv')

In [117]:
dna['Kingdom'].value_counts()

bct    2919
vrl    2831
pln    2523
vrt    2077
inv    1345
mam     572
phg     220
rod     215
pri     180
arc     126
plm      18
Name: Kingdom, dtype: int64

In [118]:
dna

,Kingdom,DNAtype,SpeciesID,Ncodons,SpeciesName,UUU,UUC,UUA,UUG,CUU,...,CGG,AGA,AGG,GAU,GAC,GAA,GAG,UAA,UAG,UGA
0,vrl,0,100217,1995,Epizootic haematopoietic necrosis virus,0.01654,0.01203,0.00050,0.00351,0.01203,...,0.00451,0.01303,0.03559,0.01003,0.04612,0.01203,0.04361,0.00251,0.00050,0.00000
1,vrl,0,100220,1474,Bohle iridovirus,0.02714,0.01357,0.00068,0.00678,0.00407,...,0.00136,0.01696,0.03596,0.01221,0.04545,0.01560,0.04410,0.00271,0.00068,0.00000
2,vrl,0,100755,4862,Sweet potato leaf curl virus,0.01974,0.02180,0.01357,0.01543,0.00782,...,0.00596,0.01974,0.02489,0.03126,0.02036,0.02242,0.02468,0.00391,0.00000,0.00144
3,vrl,0,100880,1915,Northern cereal mosaic virus,0.01775,0.02245,0.01619,0.00992,0.01567,...,0.00366,0.01410,0.01671,0.03760,0.01932,0.03029,0.03446,0.00261,0.00157,0.00000
4,vrl,0,100887,22831,Soil-borne cereal mosaic virus,0.02816,0.01371,0.00767,0.03679,0.01380,...,0.00604,0.01494,0.01734,0.04148,0.02483,0.03359,0.03679,0.00000,0.00044,0.00131
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13021,pri,0,9601,1097,Pongo pygmaeus abelii,0.02552,0.03555,0.00547,0.01367,0.01276,...,0.00820,0.01367,0.01094,0.01367,0.02279,0.02005,0.04102,0.00091,0.00091,0.00638
13022,pri,1,9601,2067,mitochondrion Pongo pygmaeus abelii,0.01258,0.03193,0.01984,0.00629,0.01451,...,0.00145,0.00000,0.00048,0.00194,0.01306,0.01838,0.00677,0.00242,0.00097,0.01887
13023,pri,1,9602,1686,mitochondrion Pongo pygmaeus pygmaeus,0.01423,0.03321,0.01661,0.00356,0.01127,...,0.00000,0.00000,0.00000,0.00178,0.01661,0.02788,0.00297,0.00356,0.00119,0.02017
13024,pri,0,9606,40662582,Homo sapiens,0.01757,0.02028,0.00767,0.01293,0.01319,...,0.01142,0.01217,0.01196,0.02178,0.02510,0.02896,0.03959,0.00099,0.00079,0.00156
13025,pri,1,9606,8998998,mitochondrion Homo sapiens,0.01778,0.03724,0.01732,0.00600,0.01689,...,0.00083,0.00041,0.00041,0.00451,0.01402,0.01651,0.00783,0.00156,0.00114,0.02161

In [119]:
dna.drop(columns=['DNAtype','SpeciesID','Ncodons','SpeciesName'],inplace=True)

In [120]:
dna

,Kingdom,UUU,UUC,UUA,UUG,CUU,CUC,CUA,CUG,AUU,...,CGG,AGA,AGG,GAU,GAC,GAA,GAG,UAA,UAG,UGA
0,vrl,0.01654,0.01203,0.00050,0.00351,0.01203,0.03208,0.00100,0.04010,0.00551,...,0.00451,0.01303,0.03559,0.01003,0.04612,0.01203,0.04361,0.00251,0.00050,0.00000
1,vrl,0.02714,0.01357,0.00068,0.00678,0.00407,0.02849,0.00204,0.04410,0.01153,...,0.00136,0.01696,0.03596,0.01221,0.04545,0.01560,0.04410,0.00271,0.00068,0.00000
2,vrl,0.01974,0.02180,0.01357,0.01543,0.00782,0.01111,0.01028,0.01193,0.02283,...,0.00596,0.01974,0.02489,0.03126,0.02036,0.02242,0.02468,0.00391,0.00000,0.00144
3,vrl,0.01775,0.02245,0.01619,0.00992,0.01567,0.01358,0.00940,0.01723,0.02402,...,0.00366,0.01410,0.01671,0.03760,0.01932,0.03029,0.03446,0.00261,0.00157,0.00000
4,vrl,0.02816,0.01371,0.00767,0.03679,0.01380,0.00548,0.00473,0.02076,0.02716,...,0.00604,0.01494,0.01734,0.04148,0.02483,0.03359,0.03679,0.00000,0.00044,0.00131
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13021,pri,0.02552,0.03555,0.00547,0.01367,0.01276,0.02097,0.00820,0.03555,0.01459,...,0.00820,0.01367,0.01094,0.01367,0.02279,0.02005,0.04102,0.00091,0.00091,0.00638
13022,pri,0.01258,0.03193,0.01984,0.00629,0.01451,0.05322,0.07644,0.01258,0.03096,...,0.00145,0.00000,0.00048,0.00194,0.01306,0.01838,0.00677,0.00242,0.00097,0.01887
13023,pri,0.01423,0.03321,0.01661,0.00356,0.01127,0.05042,0.09609,0.01068,0.02728,...,0.00000,0.00000,0.00000,0.00178,0.01661,0.02788,0.00297,0.00356,0.00119,0.02017
13024,pri,0.01757,0.02028,0.00767,0.01293,0.01319,0.01959,0.00715,0.03964,0.01600,...,0.01142,0.01217,0.01196,0.02178,0.02510,0.02896,0.03959,0.00099,0.00079,0.00156
13025,pri,0.01778,0.03724,0.01732,0.00600,0.01689,0.03854,0.07000,0.01308,0.03391,...,0.00083,0.00041,0.00041,0.00451,0.01402,0.01651,0.00783,0.00156,0.00114,0.02161

In [121]:
data = dna.iloc[:,1:].astype(float)

In [122]:
data

,UUU,UUC,UUA,UUG,CUU,CUC,CUA,CUG,AUU,AUC,...,CGG,AGA,AGG,GAU,GAC,GAA,GAG,UAA,UAG,UGA
0,0.01654,0.01203,0.00050,0.00351,0.01203,0.03208,0.00100,0.04010,0.00551,0.02005,...,0.00451,0.01303,0.03559,0.01003,0.04612,0.01203,0.04361,0.00251,0.00050,0.00000
1,0.02714,0.01357,0.00068,0.00678,0.00407,0.02849,0.00204,0.04410,0.01153,0.02510,...,0.00136,0.01696,0.03596,0.01221,0.04545,0.01560,0.04410,0.00271,0.00068,0.00000
2,0.01974,0.02180,0.01357,0.01543,0.00782,0.01111,0.01028,0.01193,0.02283,0.01604,...,0.00596,0.01974,0.02489,0.03126,0.02036,0.02242,0.02468,0.00391,0.00000,0.00144
3,0.01775,0.02245,0.01619,0.00992,0.01567,0.01358,0.00940,0.01723,0.02402,0.02245,...,0.00366,0.01410,0.01671,0.03760,0.01932,0.03029,0.03446,0.00261,0.00157,0.00000
4,0.02816,0.01371,0.00767,0.03679,0.01380,0.00548,0.00473,0.02076,0.02716,0.00867,...,0.00604,0.01494,0.01734,0.04148,0.02483,0.03359,0.03679,0.00000,0.00044,0.00131
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13021,0.02552,0.03555,0.00547,0.01367,0.01276,0.02097,0.00820,0.03555,0.01459,0.03920,...,0.00820,0.01367,0.01094,0.01367,0.02279,0.02005,0.04102,0.00091,0.00091,0.00638
13022,0.01258,0.03193,0.01984,0.00629,0.01451,0.05322,0.07644,0.01258,0.03096,0.06386,...,0.00145,0.00000,0.00048,0.00194,0.01306,0.01838,0.00677,0.00242,0.00097,0.01887
13023,0.01423,0.03321,0.01661,0.00356,0.01127,0.05042,0.09609,0.01068,0.02728,0.06643,...,0.00000,0.00000,0.00000,0.00178,0.01661,0.02788,0.00297,0.00356,0.00119,0.02017
13024,0.01757,0.02028,0.00767,0.01293,0.01319,0.01959,0.00715,0.03964,0.01600,0.02082,...,0.01142,0.01217,0.01196,0.02178,0.02510,0.02896,0.03959,0.00099,0.00079,0.00156
13025,0.01778,0.03724,0.01732,0.00600,0.01689,0.03854,0.07000,0.01308,0.03391,0.05137,...,0.00083,0.00041,0.00041,0.00451,0.01402,0.01651,0.00783,0.00156,0.00114,0.02161

In [44]:

# calculate Euclidean distance
def euclDistance(vector1, vector2):
	return sqrt(sum(power(vector2 - vector1, 2)))
 
# init centroids with random samples
def initCentroids(dataSet, k):
	numSamples, dim = dataSet.shape
	centroids = zeros((k, dim))
	for i in range(k):
		index = int(random.uniform(0, numSamples))
		centroids[i, :] = dataSet[index, :]
	return centroids
 
# k-means cluster
def kmeans(dataSet, k):
	numSamples = dataSet.shape[0]
	# first column stores which cluster this sample belongs to,
	# second column stores the error between this sample and its centroid
	clusterAssment = mat(zeros((numSamples, 2)))
	clusterChanged = True
 
	## step 1: init centroids
	centroids = initCentroids(dataSet, k)
 
	while clusterChanged:
		clusterChanged = False
		## for each sample
		for i in range(numSamples):
			minDist  = 100000.0
			minIndex = 0
			## for each centroid
			## step 2: find the centroid who is closest
			for j in range(k):
				distance = euclDistance(centroids[j, :], dataSet[i, :])
				if distance < minDist:
					minDist  = distance
					minIndex = j
			
			## step 3: update its cluster
			if clusterAssment[i, 0] != minIndex:
				clusterChanged = True
				clusterAssment[i, :] = minIndex, minDist**2
 
		## step 4: update centroids
		for j in range(k):
			pointsInCluster = dataSet[nonzero(clusterAssment[:, 0].A == j)[0]]
			centroids[j, :] = mean(pointsInCluster, axis = 0)
 
	print('Congratulations, cluster complete!')
	return centroids, clusterAssment
 
# show your cluster only available with 2-D data
def showCluster(dataSet, k, centroids, clusterAssment):
	numSamples, dim = dataSet.shape
	if dim != 2:
		print("Sorry! I can not draw because the dimension of your data is not 2!")
		return 1
 
	mark = ['or', 'ob', 'og', 'ok', '^r', '+r', 'sr', 'dr', '<r', 'pr']
	if k > len(mark):
		print("Sorry! Your k is too large! please contact Zouxy")
		return 1
 
	# draw all samples
	for i in range(numSamples):
		markIndex = int(clusterAssment[i, 0])
		plt.plot(dataSet[i, 0], dataSet[i, 1], mark[markIndex])
 
	mark = ['Dr', 'Db', 'Dg', 'Dk', '^b', '+b', 'sb', 'db', '<b', 'pb']
	# draw the centroids
	for i in range(k):
		plt.plot(centroids[i, 0], centroids[i, 1], mark[i], markersize = 12)
 
	plt.show()

In [109]:
## step 1: load data
print("step 1: load data...")

 
## step 2: clustering...
print("step 2: clustering...")
dataSet = mat(data.values)
k = 5
centroids, clusterAssment = kmeans(dataSet, k)
 
## step 3: show the result
print("step 3: show the result...")
showCluster(dataSet, k, centroids, clusterAssment)

step 1: load data...
step 2: clustering...
Congratulations, cluster complete!
step 3: show the result...
Sorry! I can not draw because the dimension of your data is not 2!

1

In [80]:
centroids

array([[0.02023089, 0.02128655, 0.01128049, 0.01745051, 0.01646271,
        0.01514029, 0.00891863, 0.01895706, 0.02183217, 0.02073877,
        0.01192259, 0.02474534, 0.02001051, 0.01588452, 0.01114803,
        0.01985617, 0.02280943, 0.01957718, 0.01926976, 0.01093687,
        0.01474123, 0.01136277, 0.01601194, 0.00850632, 0.01398951,
        0.01961059, 0.01692411, 0.01892304, 0.0118456 , 0.01502525,
        0.01287291, 0.01374887, 0.00769721, 0.01129399, 0.01267802,
        0.0167991 , 0.01684879, 0.0167236 , 0.00929325, 0.01672437,
        0.01732737, 0.01954717, 0.0202315 , 0.02237329, 0.02324242,
        0.0096311 , 0.01002518, 0.01240467, 0.01167613, 0.0275373 ,
        0.02990682, 0.0093566 , 0.00854956, 0.00606402, 0.00532025,
        0.01285437, 0.01042194, 0.02913539, 0.02330791, 0.03013512,
        0.02783277, 0.00140573, 0.00065024, 0.00098439],
       [0.04390158, 0.01454046, 0.04407068, 0.01843313, 0.01900702,
        0.00509381, 0.01265832, 0.00586522, 0.04419394, 0.01320457,
        0.02692747, 0.02110477, 0.0247988 , 0.00652367, 0.01988626,
        0.00941564, 0.02370619, 0.00730522, 0.0188329 , 0.00541375,
        0.0149087 , 0.00469742, 0.01422592, 0.00384988, 0.01145955,
        0.02230062, 0.00711475, 0.02019417, 0.00829373, 0.02291987,
        0.00727827, 0.01911715, 0.00488408, 0.01543853, 0.00584691,
        0.021329  , 0.00755515, 0.01952776, 0.00505989, 0.03264385,
        0.0100327 , 0.02545454, 0.00813601, 0.04024011, 0.01402044,
        0.00990874, 0.00370053, 0.01655436, 0.00562886, 0.04759434,
        0.01583094, 0.00982229, 0.00341991, 0.00755677, 0.0025933 ,
        0.01629815, 0.00478445, 0.03463071, 0.01099897, 0.03996431,
        0.01317075, 0.00200158, 0.00056639, 0.00356027],
       [0.00815055, 0.0283642 , 0.00171865, 0.00953781, 0.00787258,
        0.02729062, 0.002713  , 0.04505226, 0.00909722, 0.03292234,
        0.00276762, 0.02299687, 0.00829406, 0.03000069, 0.00415513,
        0.03150572, 0.01236281, 0.04907757, 0.01101289, 0.03369967,
        0.00657124, 0.01904263, 0.00567571, 0.0232798 , 0.01483832,
        0.0138036 , 0.04436923, 0.0092602 , 0.01345121, 0.00523548,
        0.01603332, 0.00401294, 0.01510554, 0.00415822, 0.01710315,
        0.00585652, 0.02975116, 0.00541715, 0.01646538, 0.00708125,
        0.02045191, 0.0072354 , 0.02827384, 0.00738634, 0.02520437,
        0.00296514, 0.01032182, 0.00659073, 0.01696253, 0.00900226,
        0.02930279, 0.00831815, 0.02857214, 0.00428168, 0.01472356,
        0.00289549, 0.00546535, 0.01601851, 0.04086332, 0.01836565,
        0.03882338, 0.0008155 , 0.0005077 , 0.00154933],
       [0.02429633, 0.03628646, 0.0273026 , 0.00443983, 0.02834119,
        0.03568554, 0.06624878, 0.0105991 , 0.03916475, 0.04426672,
        0.03530918, 0.01106569, 0.01071804, 0.01204034, 0.01931944,
        0.00455681, 0.01486851, 0.03358761, 0.02616331, 0.00228102,
        0.01179649, 0.02082794, 0.02602144, 0.00210463, 0.00335294,
        0.00769817, 0.01767404, 0.0231063 , 0.00789247, 0.01116915,
        0.01978971, 0.02437549, 0.00187455, 0.00277982, 0.00914633,
        0.01580828, 0.03217825, 0.03647297, 0.00265505, 0.01184119,
        0.01806902, 0.02150896, 0.00298425, 0.01218505, 0.02708105,
        0.00211555, 0.00480245, 0.00708266, 0.01802022, 0.02208477,
        0.00278871, 0.00206343, 0.00376881, 0.01066415, 0.0013321 ,
        0.00067289, 0.00019541, 0.00557694, 0.01237367, 0.01686157,
        0.00356453, 0.00243414, 0.00055684, 0.02610451]])

In [110]:
clusterAssment

matrix([[1.00000000e+00, 4.91923288e-03],
        [1.00000000e+00, 4.68625521e-03],
        [1.00000000e+00, 2.59466621e-03],
        ...,
        [2.00000000e+00, 7.77903200e-03],
        [1.00000000e+00, 1.72631474e-03],
        [2.00000000e+00, 6.91266820e-03]])

In [111]:
result = pd.DataFrame(clusterAssment)

In [112]:
result.columns = ['class','rate']

In [113]:
result

       class      rate
0        1.0  0.004919
1        1.0  0.004686
2        1.0  0.002595
3        3.0  0.002838
4        3.0  0.003783
...      ...       ...
13021    1.0  0.003800
13022    2.0  0.007743
13023    2.0  0.007779
13024    1.0  0.001726
13025    2.0  0.006913

[13026 rows x 2 columns]

In [124]:
classed = pd.concat([dna,result],axis=1)
classed

,Kingdom,UUU,UUC,UUA,UUG,CUU,CUC,CUA,CUG,AUU,...,AGG,GAU,GAC,GAA,GAG,UAA,UAG,UGA,class,rate
0,vrl,0.01654,0.01203,0.00050,0.00351,0.01203,0.03208,0.00100,0.04010,0.00551,...,0.03559,0.01003,0.04612,0.01203,0.04361,0.00251,0.00050,0.00000,1.0,0.004919
1,vrl,0.02714,0.01357,0.00068,0.00678,0.00407,0.02849,0.00204,0.04410,0.01153,...,0.03596,0.01221,0.04545,0.01560,0.04410,0.00271,0.00068,0.00000,1.0,0.004686
2,vrl,0.01974,0.02180,0.01357,0.01543,0.00782,0.01111,0.01028,0.01193,0.02283,...,0.02489,0.03126,0.02036,0.02242,0.02468,0.00391,0.00000,0.00144,1.0,0.002595
3,vrl,0.01775,0.02245,0.01619,0.00992,0.01567,0.01358,0.00940,0.01723,0.02402,...,0.01671,0.03760,0.01932,0.03029,0.03446,0.00261,0.00157,0.00000,3.0,0.002838
4,vrl,0.02816,0.01371,0.00767,0.03679,0.01380,0.00548,0.00473,0.02076,0.02716,...,0.01734,0.04148,0.02483,0.03359,0.03679,0.00000,0.00044,0.00131,3.0,0.003783
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13021,pri,0.02552,0.03555,0.00547,0.01367,0.01276,0.02097,0.00820,0.03555,0.01459,...,0.01094,0.01367,0.02279,0.02005,0.04102,0.00091,0.00091,0.00638,1.0,0.003800
13022,pri,0.01258,0.03193,0.01984,0.00629,0.01451,0.05322,0.07644,0.01258,0.03096,...,0.00048,0.00194,0.01306,0.01838,0.00677,0.00242,0.00097,0.01887,2.0,0.007743
13023,pri,0.01423,0.03321,0.01661,0.00356,0.01127,0.05042,0.09609,0.01068,0.02728,...,0.00000,0.00178,0.01661,0.02788,0.00297,0.00356,0.00119,0.02017,2.0,0.007779
13024,pri,0.01757,0.02028,0.00767,0.01293,0.01319,0.01959,0.00715,0.03964,0.01600,...,0.01196,0.02178,0.02510,0.02896,0.03959,0.00099,0.00079,0.00156,1.0,0.001726
13025,pri,0.01778,0.03724,0.01732,0.00600,0.01689,0.03854,0.07000,0.01308,0.03391,...,0.00041,0.00451,0.01402,0.01651,0.00783,0.00156,0.00114,0.02161,2.0,0.006913

In [131]:
compare = classed[['Kingdom','class']]

In [138]:
class0 = compare[compare['class']==0]
class1 = compare[compare['class']==1]
class2 = compare[compare['class']==2]
class3 = compare[compare['class']==3]
class4 = compare[compare['class']==4]

In [139]:
cluster = [class0,class1,class2,class3,class4]

In [150]:
verify = []
for c in cluster:
    vrl = len(c[c['Kingdom']=='vrl'])
    bct = len(c[c['Kingdom']=='bct'])
    pln = len(c[c['Kingdom']=='pln'])
    vrt = len(c[c['Kingdom']=='vrt'])
    inv = len(c[c['Kingdom']=='inv'])
    verify.append([vrl,bct,pln,vrt,inv])
answer = pd.DataFrame(verify)

In [151]:
answer.columns = ['vrl','bct','pln','vrt','inv']

In [152]:
answer

    vrl   bct  pln   vrt  inv
0    48   192  610    44  390
1  1045   529  866   410  516
2     2     0    3  1553   33
3  1674  1067  881    50  351
4    62  1131  163    20   55