In [2]:
import pandas as pd
import numpy as np
from numpy import *
import matplotlib.pyplot as plt
from scipy.spatial.distance import pdist

In [3]:
dna = pd.read_csv('codon_usage.csv')

In [4]:
dna['Kingdom'].value_counts()

bct    2919
vrl    2831
pln    2523
vrt    2077
inv    1345
mam     572
phg     220
rod     215
pri     180
arc     126
plm      18
Name: Kingdom, dtype: int64

In [5]:
dna

,Kingdom,DNAtype,SpeciesID,Ncodons,SpeciesName,UUU,UUC,UUA,UUG,CUU,...,CGG,AGA,AGG,GAU,GAC,GAA,GAG,UAA,UAG,UGA
0,vrl,0,100217,1995,Epizootic haematopoietic necrosis virus,0.01654,0.01203,0.00050,0.00351,0.01203,...,0.00451,0.01303,0.03559,0.01003,0.04612,0.01203,0.04361,0.00251,0.00050,0.00000
1,vrl,0,100220,1474,Bohle iridovirus,0.02714,0.01357,0.00068,0.00678,0.00407,...,0.00136,0.01696,0.03596,0.01221,0.04545,0.01560,0.04410,0.00271,0.00068,0.00000
2,vrl,0,100755,4862,Sweet potato leaf curl virus,0.01974,0.02180,0.01357,0.01543,0.00782,...,0.00596,0.01974,0.02489,0.03126,0.02036,0.02242,0.02468,0.00391,0.00000,0.00144
3,vrl,0,100880,1915,Northern cereal mosaic virus,0.01775,0.02245,0.01619,0.00992,0.01567,...,0.00366,0.01410,0.01671,0.03760,0.01932,0.03029,0.03446,0.00261,0.00157,0.00000
4,vrl,0,100887,22831,Soil-borne cereal mosaic virus,0.02816,0.01371,0.00767,0.03679,0.01380,...,0.00604,0.01494,0.01734,0.04148,0.02483,0.03359,0.03679,0.00000,0.00044,0.00131
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13021,pri,0,9601,1097,Pongo pygmaeus abelii,0.02552,0.03555,0.00547,0.01367,0.01276,...,0.00820,0.01367,0.01094,0.01367,0.02279,0.02005,0.04102,0.00091,0.00091,0.00638
13022,pri,1,9601,2067,mitochondrion Pongo pygmaeus abelii,0.01258,0.03193,0.01984,0.00629,0.01451,...,0.00145,0.00000,0.00048,0.00194,0.01306,0.01838,0.00677,0.00242,0.00097,0.01887
13023,pri,1,9602,1686,mitochondrion Pongo pygmaeus pygmaeus,0.01423,0.03321,0.01661,0.00356,0.01127,...,0.00000,0.00000,0.00000,0.00178,0.01661,0.02788,0.00297,0.00356,0.00119,0.02017
13024,pri,0,9606,40662582,Homo sapiens,0.01757,0.02028,0.00767,0.01293,0.01319,...,0.01142,0.01217,0.01196,0.02178,0.02510,0.02896,0.03959,0.00099,0.00079,0.00156
13025,pri,1,9606,8998998,mitochondrion Homo sapiens,0.01778,0.03724,0.01732,0.00600,0.01689,...,0.00083,0.00041,0.00041,0.00451,0.01402,0.01651,0.00783,0.00156,0.00114,0.02161

In [6]:
dna.drop(columns=['DNAtype','SpeciesID','Ncodons','SpeciesName'],inplace=True)

In [7]:
dna

,Kingdom,UUU,UUC,UUA,UUG,CUU,CUC,CUA,CUG,AUU,...,CGG,AGA,AGG,GAU,GAC,GAA,GAG,UAA,UAG,UGA
0,vrl,0.01654,0.01203,0.00050,0.00351,0.01203,0.03208,0.00100,0.04010,0.00551,...,0.00451,0.01303,0.03559,0.01003,0.04612,0.01203,0.04361,0.00251,0.00050,0.00000
1,vrl,0.02714,0.01357,0.00068,0.00678,0.00407,0.02849,0.00204,0.04410,0.01153,...,0.00136,0.01696,0.03596,0.01221,0.04545,0.01560,0.04410,0.00271,0.00068,0.00000
2,vrl,0.01974,0.02180,0.01357,0.01543,0.00782,0.01111,0.01028,0.01193,0.02283,...,0.00596,0.01974,0.02489,0.03126,0.02036,0.02242,0.02468,0.00391,0.00000,0.00144
3,vrl,0.01775,0.02245,0.01619,0.00992,0.01567,0.01358,0.00940,0.01723,0.02402,...,0.00366,0.01410,0.01671,0.03760,0.01932,0.03029,0.03446,0.00261,0.00157,0.00000
4,vrl,0.02816,0.01371,0.00767,0.03679,0.01380,0.00548,0.00473,0.02076,0.02716,...,0.00604,0.01494,0.01734,0.04148,0.02483,0.03359,0.03679,0.00000,0.00044,0.00131
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13021,pri,0.02552,0.03555,0.00547,0.01367,0.01276,0.02097,0.00820,0.03555,0.01459,...,0.00820,0.01367,0.01094,0.01367,0.02279,0.02005,0.04102,0.00091,0.00091,0.00638
13022,pri,0.01258,0.03193,0.01984,0.00629,0.01451,0.05322,0.07644,0.01258,0.03096,...,0.00145,0.00000,0.00048,0.00194,0.01306,0.01838,0.00677,0.00242,0.00097,0.01887
13023,pri,0.01423,0.03321,0.01661,0.00356,0.01127,0.05042,0.09609,0.01068,0.02728,...,0.00000,0.00000,0.00000,0.00178,0.01661,0.02788,0.00297,0.00356,0.00119,0.02017
13024,pri,0.01757,0.02028,0.00767,0.01293,0.01319,0.01959,0.00715,0.03964,0.01600,...,0.01142,0.01217,0.01196,0.02178,0.02510,0.02896,0.03959,0.00099,0.00079,0.00156
13025,pri,0.01778,0.03724,0.01732,0.00600,0.01689,0.03854,0.07000,0.01308,0.03391,...,0.00083,0.00041,0.00041,0.00451,0.01402,0.01651,0.00783,0.00156,0.00114,0.02161

In [8]:
data = dna.iloc[:,1:].astype(float)

In [9]:
data

,UUU,UUC,UUA,UUG,CUU,CUC,CUA,CUG,AUU,AUC,...,CGG,AGA,AGG,GAU,GAC,GAA,GAG,UAA,UAG,UGA
0,0.01654,0.01203,0.00050,0.00351,0.01203,0.03208,0.00100,0.04010,0.00551,0.02005,...,0.00451,0.01303,0.03559,0.01003,0.04612,0.01203,0.04361,0.00251,0.00050,0.00000
1,0.02714,0.01357,0.00068,0.00678,0.00407,0.02849,0.00204,0.04410,0.01153,0.02510,...,0.00136,0.01696,0.03596,0.01221,0.04545,0.01560,0.04410,0.00271,0.00068,0.00000
2,0.01974,0.02180,0.01357,0.01543,0.00782,0.01111,0.01028,0.01193,0.02283,0.01604,...,0.00596,0.01974,0.02489,0.03126,0.02036,0.02242,0.02468,0.00391,0.00000,0.00144
3,0.01775,0.02245,0.01619,0.00992,0.01567,0.01358,0.00940,0.01723,0.02402,0.02245,...,0.00366,0.01410,0.01671,0.03760,0.01932,0.03029,0.03446,0.00261,0.00157,0.00000
4,0.02816,0.01371,0.00767,0.03679,0.01380,0.00548,0.00473,0.02076,0.02716,0.00867,...,0.00604,0.01494,0.01734,0.04148,0.02483,0.03359,0.03679,0.00000,0.00044,0.00131
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13021,0.02552,0.03555,0.00547,0.01367,0.01276,0.02097,0.00820,0.03555,0.01459,0.03920,...,0.00820,0.01367,0.01094,0.01367,0.02279,0.02005,0.04102,0.00091,0.00091,0.00638
13022,0.01258,0.03193,0.01984,0.00629,0.01451,0.05322,0.07644,0.01258,0.03096,0.06386,...,0.00145,0.00000,0.00048,0.00194,0.01306,0.01838,0.00677,0.00242,0.00097,0.01887
13023,0.01423,0.03321,0.01661,0.00356,0.01127,0.05042,0.09609,0.01068,0.02728,0.06643,...,0.00000,0.00000,0.00000,0.00178,0.01661,0.02788,0.00297,0.00356,0.00119,0.02017
13024,0.01757,0.02028,0.00767,0.01293,0.01319,0.01959,0.00715,0.03964,0.01600,0.02082,...,0.01142,0.01217,0.01196,0.02178,0.02510,0.02896,0.03959,0.00099,0.00079,0.00156
13025,0.01778,0.03724,0.01732,0.00600,0.01689,0.03854,0.07000,0.01308,0.03391,0.05137,...,0.00083,0.00041,0.00041,0.00451,0.01402,0.01651,0.00783,0.00156,0.00114,0.02161

In [10]:

# calculate Euclidean distance
def euclDistance(vector1, vector2):
	return sqrt(sum(power(vector2 - vector1, 2)))

# calculate Manhattan distance
def manhattanDistance(vector1, vector2):
	return sum(abs(vector1-vector2))

# calculate Cosine distance
def cosineDistance(vector1, vector2):
	return pdist(np.vstack([vector1, vector2]), 'cosine')[0]
 
# init centroids with random samples
def initCentroids(dataSet, k):
	numSamples, dim = dataSet.shape
	centroids = zeros((k, dim))
	for i in range(k):
		index = int(random.uniform(0, numSamples))
		centroids[i, :] = dataSet[index, :]
	return centroids
 
# k-means cluster
def kmeans(dataSet, k):
	numSamples = dataSet.shape[0]
	# first column stores which cluster this sample belongs to,
	# second column stores the error between this sample and its centroid
	clusterAssment = mat(zeros((numSamples, 2)))
	clusterChanged = True
 
	## step 1: init centroids
	centroids = initCentroids(dataSet, k)
 
	while clusterChanged:
		clusterChanged = False
		## for each sample
		for i in range(numSamples):
			minDist  = 100000.0
			minIndex = 0
			## for each centroid
			## step 2: find the centroid who is closest
			for j in range(k):
				distance = cosineDistance(centroids[j, :], dataSet[i, :])
				if distance < minDist:
					minDist  = distance
					minIndex = j
			
			## step 3: update its cluster
			if clusterAssment[i, 0] != minIndex:
				clusterChanged = True
				clusterAssment[i, :] = minIndex, minDist**2
 
		## step 4: update centroids
		for j in range(k):
			pointsInCluster = dataSet[nonzero(clusterAssment[:, 0].A == j)[0]]
			centroids[j, :] = mean(pointsInCluster, axis = 0)
 
	print('Congratulations, cluster complete!')
	return centroids, clusterAssment
 
# show your cluster only available with 2-D data
def showCluster(dataSet, k, centroids, clusterAssment):
	numSamples, dim = dataSet.shape
	if dim != 2:
		print("Sorry! I can not draw because the dimension of your data is not 2!")
		return 1
 
	mark = ['or', 'ob', 'og', 'ok', '^r', '+r', 'sr', 'dr', '<r', 'pr']
	if k > len(mark):
		print("Sorry! Your k is too large! please contact Zouxy")
		return 1
 
	# draw all samples
	for i in range(numSamples):
		markIndex = int(clusterAssment[i, 0])
		plt.plot(dataSet[i, 0], dataSet[i, 1], mark[markIndex])
 
	mark = ['Dr', 'Db', 'Dg', 'Dk', '^b', '+b', 'sb', 'db', '<b', 'pb']
	# draw the centroids
	for i in range(k):
		plt.plot(centroids[i, 0], centroids[i, 1], mark[i], markersize = 12)
 
	plt.show()

In [11]:
## step 1: load data
print("step 1: load data...")

 
## step 2: clustering...
print("step 2: clustering...")
dataSet = mat(data.values)
k = 5
centroids, clusterAssment = kmeans(dataSet, k)
 
## step 3: show the result
print("step 3: show the result...")
showCluster(dataSet, k, centroids, clusterAssment)

step 1: load data...
step 2: clustering...
Congratulations, cluster complete!
step 3: show the result...
Sorry! I can not draw because the dimension of your data is not 2!

1

In [145]:
centroids

array([[0.06199018, 0.01596713, 0.06198665, 0.02012747, 0.02123991,
        0.00427105, 0.014678  , 0.00513835, 0.05525774, 0.01189833,
        0.03687771, 0.01796128, 0.0232339 , 0.00504247, 0.02013207,
        0.00777943, 0.02044907, 0.00582139, 0.01306969, 0.0032941 ,
        0.0144377 , 0.00486875, 0.01220393, 0.00283205, 0.0107593 ,
        0.01778306, 0.00408881, 0.01919491, 0.00941338, 0.0291015 ,
        0.00801185, 0.0215674 , 0.00515491, 0.01567486, 0.00362947,
        0.01970711, 0.00560894, 0.01495092, 0.00313593, 0.03988273,
        0.00832588, 0.02251567, 0.00521501, 0.04375546, 0.01012251,
        0.00992207, 0.00240808, 0.01985322, 0.00526563, 0.04515528,
        0.01128262, 0.00810055, 0.00224221, 0.00965311, 0.00308063,
        0.01646098, 0.00429736, 0.02671181, 0.0062426 , 0.03145204,
        0.009211  , 0.00204357, 0.00053553, 0.00791934],
       [0.0275963 , 0.01638173, 0.02352512, 0.01838257, 0.01787395,
        0.00849267, 0.01062447, 0.00960621, 0.03120718, 0.01574537,
        0.01733927, 0.02401649, 0.02460454, 0.01016589, 0.01641484,
        0.01345234, 0.02468484, 0.01123083, 0.02182719, 0.00782073,
        0.01525435, 0.00656556, 0.01653273, 0.00572915, 0.0127607 ,
        0.02306925, 0.01090399, 0.01988795, 0.00901246, 0.01772482,
        0.00856696, 0.01691699, 0.00592692, 0.01400911, 0.00897094,
        0.02053393, 0.01088508, 0.02090496, 0.00739686, 0.0241306 ,
        0.01307761, 0.02506324, 0.01367457, 0.03282671, 0.01885292,
        0.01053728, 0.00656445, 0.01451844, 0.00817033, 0.0407419 ,
        0.02382976, 0.01039145, 0.00525069, 0.00611355, 0.00323244,
        0.01570895, 0.00793071, 0.03677815, 0.01702388, 0.03979369,
        0.02000954, 0.00179292, 0.00060056, 0.0008406 ],
       [0.0170858 , 0.02351208, 0.00736546, 0.0156983 , 0.01487069,
        0.01870837, 0.00778338, 0.02459361, 0.01817802, 0.02389303,
        0.00944397, 0.02485433, 0.01705034, 0.018936  , 0.00908374,
        0.02296072, 0.0219186 , 0.02487131, 0.01752941, 0.01288143,
        0.01409854, 0.01410118, 0.01456355, 0.0100163 , 0.01432049,
        0.01843011, 0.02109018, 0.0183582 , 0.01280282, 0.01344759,
        0.01524895, 0.01140466, 0.0083877 , 0.00978227, 0.01462637,
        0.01489084, 0.02051948, 0.01433868, 0.01015673, 0.01322744,
        0.01955326, 0.01643481, 0.02319244, 0.01734116, 0.02541815,
        0.00832168, 0.01137542, 0.01046536, 0.01308366, 0.02250055,
        0.0316549 , 0.00890608, 0.01079576, 0.00592488, 0.00637513,
        0.01063349, 0.01038899, 0.0250835 , 0.02684547, 0.02617078,
        0.0316151 , 0.0012345 , 0.00066366, 0.00099051],
       [0.0242251 , 0.03633316, 0.02717239, 0.0044327 , 0.02835138,
        0.03576069, 0.0663233 , 0.01062729, 0.03907774, 0.04433526,
        0.03522343, 0.01108005, 0.01070693, 0.01206553, 0.01929974,
        0.00456649, 0.01485863, 0.03363739, 0.02616473, 0.00229313,
        0.01178658, 0.02087312, 0.02601967, 0.0021047 , 0.00336486,
        0.00767762, 0.01769284, 0.02309425, 0.0079019 , 0.01114349,
        0.01981801, 0.02434126, 0.00188144, 0.00276321, 0.00915448,
        0.01579204, 0.03221447, 0.03646243, 0.00265939, 0.01181163,
        0.01809097, 0.02150572, 0.00299795, 0.01215486, 0.02710252,
        0.00210895, 0.0048062 , 0.00707671, 0.01803498, 0.02207756,
        0.00279825, 0.00205896, 0.00377095, 0.01066609, 0.00133576,
        0.00066957, 0.00019409, 0.00556493, 0.01238573, 0.01684948,
        0.0035654 , 0.00243407, 0.0005561 , 0.02609991],
       [0.00699865, 0.02852676, 0.00136292, 0.00896482, 0.00704798,
        0.02799387, 0.00231639, 0.04756751, 0.00794877, 0.03368786,
        0.00219067, 0.02240078, 0.00728337, 0.03122892, 0.00379319,
        0.03262116, 0.01081435, 0.05218387, 0.01054244, 0.03765687,
        0.00539684, 0.01902763, 0.00472432, 0.0256946 , 0.01496343,
        0.01303009, 0.04766857, 0.00815258, 0.01381626, 0.00395499,
        0.01535908, 0.00330058, 0.01622624, 0.00360005, 0.0170144 ,
        0.00467805, 0.03047933, 0.00446325, 0.01755804, 0.00662443,
        0.01989362, 0.00649871, 0.02837276, 0.00656589, 0.02435596,
        0.00231283, 0.00983096, 0.00636035, 0.01720857, 0.00768678,
        0.02785258, 0.00833507, 0.03147537, 0.0041405 , 0.0162356 ,
        0.00210155, 0.004503  , 0.01517532, 0.04240201, 0.01807977,
        0.03884161, 0.00074249, 0.0004983 , 0.00166763]])

In [43]:
y = clusterAssment[:,0]
y = column_or_1d(y, warn=True)
y

NameError: name 'column_or_1d' is not defined

In [12]:
result = pd.DataFrame(clusterAssment)

In [13]:
result.columns = ['class','rate']

In [14]:
result

       class      rate
0        1.0  0.012310
1        4.0  0.007115
2        4.0  0.004306
3        3.0  0.007961
4        3.0  0.005400
...      ...       ...
13021    4.0  0.006060
13022    2.0  0.003861
13023    2.0  0.007486
13024    4.0  0.001763
13025    2.0  0.002772

[13026 rows x 2 columns]

In [15]:
classed = pd.concat([dna,result],axis=1)
classed

,Kingdom,UUU,UUC,UUA,UUG,CUU,CUC,CUA,CUG,AUU,...,AGG,GAU,GAC,GAA,GAG,UAA,UAG,UGA,class,rate
0,vrl,0.01654,0.01203,0.00050,0.00351,0.01203,0.03208,0.00100,0.04010,0.00551,...,0.03559,0.01003,0.04612,0.01203,0.04361,0.00251,0.00050,0.00000,1.0,0.012310
1,vrl,0.02714,0.01357,0.00068,0.00678,0.00407,0.02849,0.00204,0.04410,0.01153,...,0.03596,0.01221,0.04545,0.01560,0.04410,0.00271,0.00068,0.00000,4.0,0.007115
2,vrl,0.01974,0.02180,0.01357,0.01543,0.00782,0.01111,0.01028,0.01193,0.02283,...,0.02489,0.03126,0.02036,0.02242,0.02468,0.00391,0.00000,0.00144,4.0,0.004306
3,vrl,0.01775,0.02245,0.01619,0.00992,0.01567,0.01358,0.00940,0.01723,0.02402,...,0.01671,0.03760,0.01932,0.03029,0.03446,0.00261,0.00157,0.00000,3.0,0.007961
4,vrl,0.02816,0.01371,0.00767,0.03679,0.01380,0.00548,0.00473,0.02076,0.02716,...,0.01734,0.04148,0.02483,0.03359,0.03679,0.00000,0.00044,0.00131,3.0,0.005400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13021,pri,0.02552,0.03555,0.00547,0.01367,0.01276,0.02097,0.00820,0.03555,0.01459,...,0.01094,0.01367,0.02279,0.02005,0.04102,0.00091,0.00091,0.00638,4.0,0.006060
13022,pri,0.01258,0.03193,0.01984,0.00629,0.01451,0.05322,0.07644,0.01258,0.03096,...,0.00048,0.00194,0.01306,0.01838,0.00677,0.00242,0.00097,0.01887,2.0,0.003861
13023,pri,0.01423,0.03321,0.01661,0.00356,0.01127,0.05042,0.09609,0.01068,0.02728,...,0.00000,0.00178,0.01661,0.02788,0.00297,0.00356,0.00119,0.02017,2.0,0.007486
13024,pri,0.01757,0.02028,0.00767,0.01293,0.01319,0.01959,0.00715,0.03964,0.01600,...,0.01196,0.02178,0.02510,0.02896,0.03959,0.00099,0.00079,0.00156,4.0,0.001763
13025,pri,0.01778,0.03724,0.01732,0.00600,0.01689,0.03854,0.07000,0.01308,0.03391,...,0.00041,0.00451,0.01402,0.01651,0.00783,0.00156,0.00114,0.02161,2.0,0.002772

In [23]:
k = classed.iloc[:,1:65]
X = k.values

In [27]:
l = classed.iloc[:,65]
Y = l.values

In [42]:
from sklearn import metrics
from sklearn.cluster import KMeans

standard = []
for i in range(2,10):
    dataSet = mat(data.values)
    centroids, clusterAssment = kmeans(dataSet, i)
    Y = clusterAssment[:,0]
    y_pred = KMeans(n_clusters=i, random_state=64).fit_predict(X)
    standard.append([metrics.calinski_harabasz_score(X, y_pred),metrics.calinski_harabasz_score(X, Y)])
    print(i)
standard

Congratulations, cluster complete!

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

2
Congratulations, cluster complete!

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

3
Congratulations, cluster complete!

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

4
Congratulations, cluster complete!

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

5
Congratulations, cluster complete!

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

6
Congratulations, cluster complete!

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

7
Congratulations, cluster complete!

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

8
Congratulations, cluster complete!
9

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[[3977.9119799523473, 3425.3029936486087],
 [4922.0241313202705, 4920.774986066661],
 [4546.097260577083, 4527.867143048459],
 [3946.1489689222426, 3931.8039902148103],
 [3526.6795910823707, 3494.0436272664565],
 [3167.370274048748, 3027.9496535141284],
 [2868.0847125022033, 2820.6672080376225],
 [2619.1567802205545, 2603.3969073321023]]

In [ ]:
import matplotlib.pyplot as plt

x = [2,3,4,5,6,7,8,9]
y = result
plt.plot(x, y)
plt.title('The sum of squared distances under different values of k')
plt.xlabel('k')
plt.ylabel('the sum of squared distances')
plt.show()

In [152]:
class0 = compare[compare['class']==0]
class1 = compare[compare['class']==1]
class2 = compare[compare['class']==2]
class3 = compare[compare['class']==3]
class4 = compare[compare['class']==4]

In [153]:
cluster = [class0,class1,class2,class3,class4]

In [154]:
cluster

[      Kingdom  class
 15        vrl    0.0
 19        vrl    0.0
 20        vrl    0.0
 189       vrl    0.0
 199       vrl    0.0
 ...       ...    ...
 12136     mam    0.0
 12181     mam    0.0
 12371     mam    0.0
 12372     mam    0.0
 12518     mam    0.0

 [1294 rows x 2 columns],
       Kingdom  class
 3         vrl    1.0
 4         vrl    1.0
 5         vrl    1.0
 6         vrl    1.0
 9         vrl    1.0
 ...       ...    ...
 12055     vrt    1.0
 12800     rod    1.0
 12883     pri    1.0
 12935     pri    1.0
 12936     pri    1.0

 [4124 rows x 2 columns],
       Kingdom  class
 1         vrl    2.0
 2         vrl    2.0
 7         vrl    2.0
 26        vrl    2.0
 27        vrl    2.0
 ...       ...    ...
 13015     pri    2.0
 13017     pri    2.0
 13019     pri    2.0
 13021     pri    2.0
 13024     pri    2.0

 [3585 rows x 2 columns],
       Kingdom  class
 878       vrl    3.0
 2231      vrl    3.0
 6504      pln    3.0
 7547      pln    3.0
 8121      pln    3.0
 ...       ...    ...
 13018     pri    3.0
 13020     pri    3.0
 13022     pri    3.0
 13023     pri    3.0
 13025     pri    3.0

 [2313 rows x 2 columns],
       Kingdom  class
 0         vrl    4.0
 8         vrl    4.0
 17        vrl    4.0
 18        vrl    4.0
 21        vrl    4.0
 ...       ...    ...
 12973     pri    4.0
 12975     pri    4.0
 12983     pri    4.0
 13001     pri    4.0
 13003     pri    4.0

 [1710 rows x 2 columns]]

In [155]:
verify = []
for c in cluster:
    vrl = len(c[c['Kingdom']=='vrl'])
    bct = len(c[c['Kingdom']=='bct'])
    pln = len(c[c['Kingdom']=='pln'])
    vrt = len(c[c['Kingdom']=='vrt'])
    inv = len(c[c['Kingdom']=='inv'])
    verify.append([vrl,bct,pln,vrt,inv])
answer = pd.DataFrame(verify)

In [156]:
answer.columns = ['vrl','bct','pln','vrt','inv']

In [157]:
answer

    vrl   bct  pln   vrt  inv
0    44   152  640    49  398
1  1632  1098  820    44  337
2  1058   462  860   393  496
3     2     0    3  1558   32
4    95  1207  200    33   82